FROM openjdk:8
MAINTAINER Nihar Kanwar nihar.kanwar@gmail.com
COPY ./target/calcDevops-1.0-SNAPSHOT-jar-with-dependencies.jar ./
WORKDIR ./
CMD ["java", "-jar", "calcDevops-1.0-SNAPSHOT-jar-with-dependencies.jar"]